### ISSUE TITLE
Integrating file_column in Active_scaffold

### ISSUE THREAD

**Issue by CCH4GITHUB** [activescaffold/file_column#2]
Hi Sergio

from https://github.com/activescaffold/file_column

USAGE ===== Just drop the whole directory into your application's "vendor/plugins" directory. Starting with version 1.0rc of rails, it will be automatically picked for you by rails plugin mechanism.

Currently using Rails & which don't have 'vendor/plugins' 

So I created  'vendor/plugins'  and dropped file_column folder under it

Then 
1.rails g active_scaffold:resource product_name product_description product_image
2. rails db:migrate
3. then proceeded with following steps
active_scaffold :product do |config|

    config.label = “Product Page”

    config.columns = [:product_name, :product_description, :product_image]

    config.create.multipart = true

    config.update.multipart = true

    config.columns[:product_image].label = “Product Image”

end

 what I do here is just add a field :product_image which stores the file path of the image that is updated. However just adding the product image shall not do the job, like with other fields we have to override the product_image column and form_column methods in the helper methods to use file column plugin field.

 So in our Product_Helper.rb we add  the below code

 The below code is called by the create and edit actions which shows the user a file column filed to allow upload of the image for a particular row.

 def product_image_form_column(record, input_name)

 file_column_field ‘record’, :product_image

end

 The below code is called during the list and show actions to display the image that is associated to the product.

 def product_image_column(record)

  image_tag url_for_file_column(record, “product_image“) if record.product_image

end

 In the Product.rb  (model file)

 file_column :product_image

Followed the guide as above but got this error at localhost:3000/products/index#

NoMethodError (undefined method `file_column’ for #):

class Product < ApplicationRecord
file_column :product_image
end

Q. What am I doing wrong ?

**Comment by scambra** [comment]
This is really old, I haven't used in years, rails don't support plugins since 4.0, they were deprecated on rails 3 and removed on rails 4. I don't know if this plugin works with any recent rails version.

You get undefined method file_column because rails is not reading vendor/plugins anymore, that's why you didn't have vendor/plugins directory. You should use ActiveStorage, or a gem for file uploading such as carrierwave, paperclip or dragonfly. ActiveScaffold have bridges to support them, bridge will be enabled automatically when AS detects gem is loaded, and form_ui will be set by default for those columns.
